[project]
name = "sepi-point"
version = "0.1.0"
description = "Detection of point mutation-mediated antimicrobial resistance in Staphylococcus epidermidis "
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["pandas","numpy"]

[dependency-groups]
dev = ["pytest"]

[build-system]
requires = ["uv_build>=0.6.6,<0.7"]
build-backend = "uv_build"